services:
  postgres-shard-usa:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_SHARD_USA_PASSWORD}
        - POSTGRES_USER=${DATABASE_SHARD_USA_USER}
        - POSTGRES_DB=${DATABASE_SHARD_USA_DB}
    ports:
      - 7301:5432
    volumes:
      - postgres:/data/postgres

  postgres-shard-eu:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_SHARD_EU_PASSWORD}
      - POSTGRES_USER=${DATABASE_SHARD_EU_USER}
      - POSTGRES_DB=${DATABASE_SHARD_EU_DB}
    ports:
      - 7302:5432
    volumes:
      - postgres:/data/postgres

  postgres-shard-asia:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_SHARD_ASIA_PASSWORD}
        - POSTGRES_USER=${DATABASE_SHARD_ASIA_USER}
        - POSTGRES_DB=${DATABASE_SHARD_ASIA_DB}
    ports:
      - 7303:5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
